name: Get secrets from secret manager
on: 
  workflow_dispatch
jobs:
  get-secret:
    runs-on: ubuntu-latest
    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: 'actions/checkout@v3'

    # Configure Workload Identity Federation via a credentials file.
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        token_format: 'access_token'
        create_credentials_file: true
        access_token_lifetime: "120s"
        workload_identity_provider: 'projects/543012353984/locations/global/workloadIdentityPools/dude/providers/github'
        service_account: 'githubsvc@sodium-atrium-308005.iam.gserviceaccount.com'

    # Install gcloud, `setup-gcloud` automatically picks up authentication from `auth`.
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Init
      id: init
      working-directory: ./terraform
      run: terraform init

    - name: Terraform plan
      id: plan
      working-directory: ./terraform
      run: terraform plan

    - name: Terraform apply
      id: apply
      working-directory: ./terraform
      run: terraform apply -auto-approve
      
    # Now you can run gcloud commands authenticated as the impersonated service account.
    # - id: 'gcloud'
    #   name: 'gcloud'
    #   run: |-
    #     gcloud storage buckets create gs://dude-abcd-xyz --default-storage-class=nearline --location=asia
